# Generated by Django 3.1.4 on 2020-12-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'Debit'), ('2', 'Credit')], max_length=255),
        ),
    ]
